SCP-3305 SCP-3263 fixed Ledger.Constraints.Offchain.updateUtxoIndex
input-output-hk/plutus-apps pull request #275
Opened 2022-01-24 18:23 UTC by bwbush

Prior to this commit, `Ledger.Constraints.Offchain.updateUtxoIndex` would discard lookups for inputs that aren't script outputs. However, sometimes it is necessary to include particular public-key `TxIn`s in a transaction, via `Plutus.Contract.Wallet.ExportTx.lookups`: a good example of this is when a `Plutus.Contract.Currency.OneShotCurrency` needs to consume a specified `UTxO` in its minting policy. Even though `Plutus.Constraints.Tx.mustSpendPubKeyOutput` adds a public-key input to the lookups, `updateUtxoIndex` discards that, with the result that it is only by chance that `cardano-wallet` would select that necessary input for the balanced transaction and provide it to Plutus validators. (Note that `cardano-wallet` does not automatically provide the `TxIn` in the partially constructed transaction to validators: it only provides `Cardano.Wallet.PartialTx.inputs` and the inputs it has semi-randomly chosen.) The consequence of all of this is that scripts that require a particular input will randomly fail during balancing in wallets with more than one UTxO.

This fix simply adds public-key inputs to the type `Ledger.Constraints.OffChain.ScriptOutput` so that it can also hold public-key inputs. (There might be a more descriptive name than `ScriptOutput` now.) It makes minor adjustments to the chain of functions that pass this into an unbalanced transaction before it is sent to `cardano-wallet`.

Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [x] Relevant tickets are mentioned in commit messages
    - [x] Formatting, materialized Nix files, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [x] Reviewer requested

2022-01-25 17:22 UTC, raduom approved these changes
This looks good to me, but I have not worked in this area recently, so I asked @sjoerdvisscher for a review also.

2022-01-26 10:14 UTC, sjoerdvisscher commented
The reason we removed public-key inputs is that `cardano-wallet` doesn't support it. See #57.
So it might be that we were wrongly informed, but did you check that this works with `cardano-wallet`?

2022-01-26 11:42 UTC, sjoerdvisscher requested changes
If we do this, the way to go would be to revert #57.

2022-01-26 16:48 UTC, bwbush commented
> The reason we removed public-key inputs is that `cardano-wallet` doesn't support it. See #57. So it might be that we were wrongly informed, but did you check that this works with `cardano-wallet`?

Yes, I've tested this will wallet and actual Marlowe contract endpoints. The `MustSpendPubKeyOutput` could have been named `MustSpendWalletOutput` because it just provides a `UTxO` that could reside at any of the wallet's addresses.

I stepped through each phase of wallet's processing of the request from the PAB to see how it balances the transaction: the wallet makes provision for spending particular UTxOs in the [`PartialTx.inputs`](https://github.com/input-output-hk/cardano-wallet/blob/5ad348d26313363bacec061ee963c89fd9d467b8/lib/core/src/Cardano/Wallet.hs#L1396), which is poplulated from `ExportTx`. The wallet only provides UTxOs to scripts if they are specified in `PartialTx.inputs` or if the wallet happens to select the UTxO when it balances; unfortunately, the wallet does not pass the `TxIn`s contained in `PartialTx.partialTx :: Tx AlonzoEra` to scripts involved in the transaction.

2022-01-26 16:59 UTC, bwbush commented
> If we do this, the way to go would be to revert #57.

It looks like reverting #57 would work, but I'd like to test that.

2022-01-27 20:20 UTC, bwbush commented
@sjoerdvisscher, I reverted #57 in d23de941d7b851764d77d05f846bea513f565e3a. The Marlowe PAB integration test passes (running the full Marlowe contract on our private testnet) using this revision. Would you please re-review? Thanks.

2022-01-28 10:20 UTC, sjoerdvisscher approved these changes
I like all this red :)

2022-01-28 12:52 UTC, merged