[PLT-670] Add  MustValidateIn to tx constraints
input-output-hk/plutus-apps pull request #665
Opened 2022-08-17 08:52 UTC by berewt

`MustValidateIn` is now managed in `OffChain.processConstraint`.

There's an integration test to check that `mkTx` set the `validityTimeRange` accordingly when the constraint is used.

Pre-submit checklist:
- Branch
    - [X] Tests are provided (if possible)
    - [X] Commit sequence broadly makes sense
    - [X] Key commits have useful messages
    - [X] Formatting, PNG optimization, etc. are updated
- PR
    - [X] Self-reviewed the diff
    - [X] Useful pull request description
    - [X] Reference the ADR in the PR and reference the PR in the ADR (if revelant)
    - [X] Reviewer requested

2022-08-17 13:50 UTC, koslambrou commented
For this PR, I would recreate the same tests in `Spec.TxConstraints.TimeValidity`, but for `plutus-tx-constraints` instead of `plutus-ledger-constraints` (keep the old one until we finally remove it).

2022-08-19 10:34 UTC, berewt commented
Got a failure I'm unable to explain in the `protocolV5Cardano` test.
The transaction pass despite the validityRange, not sure if it's normal due to how we build the transaction in Tx.Constraints or not.

2022-08-19 11:26 UTC, sjoerdvisscher requested changes

2022-08-19 11:26 UTC, sjoerdvisscher commented on plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
> +    = UnbalancedLedgerTx
`UnbalancedLedgerTx` sounds like it's a transaction from `cardano-ledger`. `UnbalancedEmulatorTx` is probably a better name here.

2022-08-19 11:26 UTC, sjoerdvisscher commented on plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs
> +        [ hang 2 $ vsep ["Tx (Cardano Representation):", pretty utx]
```suggestion
        [ hang 2 $ vsep ["Tx (cardano-api representation):", pretty utx]
```

2022-08-19 11:26 UTC, sjoerdvisscher commented on plutus-contract/test/Spec/TxConstraints/TimeValidity.hs
> +
Would be nice to read out the time again here and check it's within `f now`.

2022-08-22 08:23 UTC, berewt commented
`protocolV5 test` keeps failing with `Tx.Constraints`. I wonder if it can come from the way we test in the two cases: we check that the transaction is validated within its validity range in the `Tx.Constraints` case, while we are checking the validity range that is stored in `ScriptContext` in the initial case. Unfortunately, I can't use the validator as not enough `Tx.Constraints` are available on `main`.

2022-08-22 08:37 UTC, sjoerdvisscher commented
I'm fine with removing the V5 test, as long as we have a good negative test that shows the positive test doesn't succeed by accident.

2022-08-22 08:48 UTC, berewt commented
It leads to the other issue with the PR at this stage: the failing test defines an unreachable range for a `Tx` and checks that the `Tx` isn't validated after some slot. Unfortunately, the transaction isn't failing either, it's just waiting for a valid slot that doesn't (and can't) come.
I think it's ok, but maybe we  (I) should open an issue to investigate whether this behavior should be fixed.

2022-08-22 11:44 UTC, sjoerdvisscher commented on plutus-contract/test/Spec/TxConstraints/TimeValidity.hs
> +invalidContractCardano :: Ledger.Params -> Contract () Empty ContractError ()
Can you add some documentation to explain how this test works?

2022-08-22 11:45 UTC, sjoerdvisscher commented on plutus-contract/test/Spec/TxConstraints/TimeValidity.hs
> +-- We only test here if the contract ends with no valid transaction.
This comment does not match the test `assertValidatedTransactionCount 1`

2022-08-23 13:58 UTC, sjoerdvisscher approved these changes
Thanks, that makes a lot of sense with the explanation!

2022-08-23 14:01 UTC, merged