PLT-797 Fix the test(s) for bug #695
input-output-hk/plutus-apps pull request #766
Opened 2022-10-19 13:48 UTC by berewt

The bug is not really a bug, but rather a lack of API documentation. The right call to the API provides the correct outputs. 
I've modified the tests accordingly and documented `WalletState` to mitigate the risk of misinterpreting its content.

2 questions:

1. do we keep the bug test or do we remove it?
2. do we want to review how information are stored in `WalletState`?

Pre-submit checklist:
- Branch
    - [x] Tests are provided (if possible)
    - [x] Commit sequence broadly makes sense
    - [x] Key commits have useful messages
    - [ ] Formatting, PNG optimization, etc. are updated
- PR
    - [x] Self-reviewed the diff
    - [x] Useful pull request description
    - [ ] Reference the ADR in the PR and reference the PR in the ADR (if revelant)
    - [x] Reviewer requested

2022-10-20 00:54 UTC, koslambrou approved these changes

2022-10-20 00:55 UTC, koslambrou commented
1. I think we can remove bug695 test case
2. What exactly do you want to review?

2022-10-20 06:12 UTC, berewt commented
>     2. What exactly do you want to review?

There seems to be some information duplication in the emulator state between `ChainState` and `WalletStates` and it can be confusing (like, in this case, when a wallet state contains information about the whole blockchain). We also have some difficulty providing a coherent state across these duplications (see #696).
So, the main argument in favour of revisiting the `EmulatorState` is: we can probably carry less information, which could speed up the emulator and reduce discrepancies inside a state. The cons is the effort of revisiting the free monad stack and the chance to break things that are currently working.

2022-10-24 09:06 UTC, james-iohk requested changes
Thanks for removing the index override @berewt
Please may you also apply this to the MustReferenceOutput tests too?

2022-10-25 08:39 UTC, james-iohk approved these changes

2022-10-25 08:39 UTC, merged